version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hubgit-backend
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://20.110.94.67:6379